-- SELECT 함수
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;

SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID = 30;

CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20),
    SAL NUMBER(7,2)
);
SELECT * FROM EMP01;

CREATE TABLE EMPLOYEES02
AS
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES02;

ALTER TABLE EMP01
ADD(JOB VARCHAR2(9));
DESC EMP01;

ALTER TABLE EMP01
MODIFY(JOB VARCHAR2(30));
DESC EMP01;

ALTER TABLE EMP01
DROP COLUMN JOB;

CREATE TABLE EMPLOYEES03
AS
SELECT * FROM EMPLOYEES02;

TRUNCATE TABLE EMPLOYEES03;
DESC EMPLOYEES03;
SELECT * FROM EMPLOYEES03;

CREATE TABLE DEPT(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

DESC DEPT;
SELECT * FROM DEPT;

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK'); -- 모든 열에 값을 대입하는 경우 DEPT후에 컬럼명을 명시하지 않아도 된다.(생략가능)
SELECT * FROM DEPT;


