-------------------Table 예제221028-------------------------------------------------------
--2[오라클] 테이블 생성 예제(문풀완)(제출완)
--1.
CREATE TABLE MEMBER(
    ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    REGNO VARCHAR2(8) NOT NULL,
    HP VARCHAR2(13),
    ADDRESS VARCHAR2(100)
);
SELECT * FROM MEMBER; -- MEMBER table 데이터 조회
DESC MEMBER; -- MEMBER table 조회
SELECT * FROM TAB; --PDB_HR 에 생성된 table 조회
--2.
CREATE TABLE BOOK(
    CODE NUMBER(4) NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    COUNT NUMBER(6),
    PRICE NUMBER(10),
    PUBLISH VARCHAR2(50)
);
SELECT * FROM BOOK;
DESC BOOK;
SELECT * FROM TAB;
--3.
CREATE TABLE BOOK_ORDER(
    NO VARCHAR2(10) NOT NULL PRIMARY KEY,
    ID VARCHAR2(20) NOT NULL,
    CODE NUMBER(4) NOT NULL,
    COUNT NUMBER(6),
    OR_DATE DATE
);
SELECT * FROM BOOK_ORDER;
DESC BOOK_ORDER;
SELECT * FROM TAB;